# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
# Make sure to check the documentation at https://goreleaser.com
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/cmd.Version={{ .Version }}
    binary: relok8s
dockers:
  -
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/vmware-tanzu/asset-relocation-tool-for-kubernetes:{{ .Tag }}"
      - "ghcr.io/vmware-tanzu/asset-relocation-tool-for-kubernetes:latest"
    build_flag_templates:
      - "--build-arg"
      - "VERSION={{ .Version }}"
    extra_files:
      - assets/docker-login.sh
archives:
  - format: tar.gz
    name_template: >-
      {{- .Binary }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
